name: Sync to Gitee Mirror

on:
  schedule:
    - cron: '0 0 1 * *'    # 每月同步一次（UTC时间）
  push:                    # 当原仓库有更新时自动触发
  workflow_dispatch:       # 允许手动触发

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "gitee.com" >> ~/.git-credentials
          echo "https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com" >> ~/.git-credentials
          git credential approve

      - name: Sync to Gitee
        run: |
          git remote add gitee https://gitee.com/xy-ylr/fixit.git
          git push --mirror gitee
        env:
          TZ: Asia/Shanghai  # 设置时区
